name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    name: Lintowanie kodu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          # Użyj stabilnej LTS wersji Node.js
          node-version: '20.x'
          cache: 'npm'

      - name: Debugowanie środowiska
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Zawartość package.json:"
          cat package.json | grep -E '"name"|"version"|"type"'
          ls -la package*.json

      - name: Instalacja zależności
        run: |
          # Bardziej elastyczna instalacja z pominięciem ścisłego sprawdzania peer dependencies
          npm install --legacy-peer-deps --omit=dev --no-fund --no-audit

      - name: Uruchomienie lintowania plików workflow
        run: |
          # Użyj actionlint do sprawdzenia plików workflow
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          ./actionlint -color

      - name: Dodanie komentarza o sukcesie
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.createComment({
              issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Weryfikacja GitHub Actions zakończona sukcesem**\n\nWszystkie pliki workflow przeszły walidację.`
            }); 